//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTitan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapManagement
    {
        public int id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.TimeSpan> InitalCap { get; set; }
        public Nullable<System.TimeSpan> PendingCap { get; set; }
    
        public virtual ClientMaster ClientMaster { get; set; }
    }
}
