//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTitan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientMaster()
        {
            this.ServiceTitanResponses = new HashSet<ServiceTitanResponse>();
            this.CapManagements = new HashSet<CapManagement>();
        }
    
        public int Id { get; set; }
        public string client_name { get; set; }
        public string agent_group { get; set; }
        public Nullable<int> tenant { get; set; }
        public string STClientSecret { get; set; }
        public Nullable<int> Cap { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public string STClientID { get; set; }
        public string MappedAgents { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceTitanResponse> ServiceTitanResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CapManagement> CapManagements { get; set; }
    }
}
