//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTitan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorHandler
    {
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> syncId { get; set; }
        public string ErrorMessage { get; set; }
        public string ErrorStacktrace { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> ServiceTitanResponseId { get; set; }
    }
}
