//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTitan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceStatusHistory
    {
        public int ID { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> SyncHistoryId { get; set; }
        public Nullable<int> ServiceTitanResponseId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
