//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTitan.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RyanStomelEntities : DbContext
    {
        public RyanStomelEntities()
            : base("name=RyanStomelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientMaster> ClientMasters { get; set; }
        public virtual DbSet<ServiceTitanResponse> ServiceTitanResponses { get; set; }
        public virtual DbSet<SyncHistory> SyncHistories { get; set; }
        public virtual DbSet<ErrorHandler> ErrorHandlers { get; set; }
        public virtual DbSet<ServiceStatusHistory> ServiceStatusHistories { get; set; }
        public virtual DbSet<CapManagement> CapManagements { get; set; }
    }
}
